name: Landscape Specialists Ltd.
favicon: null
layout_spectrum: 0.50226
typography_spectrum: 0.63573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8bc541'
    - '#3c3c3c'
    - '#818181'
  brandStrength: 0.6092727894429117
  lightness: 0.23660813248716295
  saturation: 0.11580532090738416
  rhythmicContrast: 0.9201684785075486
purpose: []
